### ISSUE TITLE
Better event reporting of resolved results (Feature request)

### ISSUE THREAD

**Issue by ccaapton** [chengr28/Pcap_DNSProxy#275]
After pcap_dnsproxy successfully resolved an address, I would like to receive some metric report, e.g if the domain is domestic or foreign. I want to do connectivity check using ping, if the domain is not reachable, then I can add the domain/ip to some proxy list. These are the approaches I can think of to report every request/reply:
- dbus broadcast
- zmq publish
- mqtt publish
- ... you name it

I can code, but I don't know where are the cut-points at which I can add hooks. I'm particularly interested in: 
1. after the local dns return, and domestic/foreign judgement logic is applied to the preliminary result
2. the point at which the final result is about to reply to the client

Could you point out where should I begin?

**Comment by chengr28** [comment]
I think that this feature is similar to running log, this feature is not necessary for the project.
About the questions, there are some advises to your own coding:
- Connectivity check using Ping/ICMP is a bad idea if you are in mainland China. HTTP/HTTPS or other often used protocols are using TCP, you should use TCPing or curl.. to check the status.
- There are lots of request processes, the main host process is EnterRequestProcess in Process.cpp and you can hook results between different(or all) processes, like local request process.
- It's difficult to log every sending or receiving call, because they are locating in every request methods. You can only log the result of this whole process easily in EnterRequestProcess.
- Domestic/foreign judgement logic is based on Local Routing list, which is CheckAddressRouting in CheckResponseData in Protocol.cpp. It will check that addresses are in the list or not and decide what the next step.
- All final result will send to requester(client) by SendToRequester in Process.cpp, also you can hook responses here.
