### ISSUE TITLE
local Pcap_DNSProxy as nginx resovler peer could not resolve some domains

### ISSUE THREAD

**Issue by jianglinchun** [chengr28/Pcap_DNSProxy#323]
nginx errors samples:

2017/12/28 13:12:48 [error] 2732#1400: *214 www.hebgb.gov.cn could not be resolved (2: Server failure), client: 127.0.0.1, server: , request: "GET http://www.hebgb.gov.cn/ HTTP/1.1", host: "www.hebgb.gov.cn"

------------
in windows command line:

nslookup
默认服务器:  bogon
Address:  10.10.10.10

> server 127.0.0.1
默认服务器:  localhost
Address:  127.0.0.1

> www.hebdg.gov.cn
服务器:  localhost
Address:  127.0.0.1

非权威应答:
名称:    www.hebdg.gov.cn
Address:  110.249.214.211

………………

**Comment by chengr28** [comment]
I don't know how nginx DNS module works, but seems that the domain can be resolved normally based on your nslookup test. I guess that nginx may have a short timeout. Pcap_DNSProxy usually need a long time (because of lots of request process) to get the correct result and make nginx timeout.

Also another possible reason is that this domain hasn't got any AAAA records and no response from all DNS when requesting AAAA.
